const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], money=n=>'฿'+Number(n||0).toLocaleString('th-TH');
const old=JSON.parse(localStorage.getItem('sdpos_v2')||'null');
const baseAccounts=[{u:'owner',p:'1234',name:'เจ้าของ',role:'owner'},{u:'staff1',p:'1111',name:'Staff 1',role:'staff'},{u:'staff2',p:'2222',name:'Staff 2',role:'staff'},{u:'staff3',p:'3333',name:'Staff 3',role:'staff'}];
const baseCats=[{id:'sourdough',name:'Sourdough'},{id:'bread',name:'ขนมปัง'},{id:'bakery',name:'เบเกอรี่'},{id:'food',name:'ของทานเล่น'}];
const defaultProducts=[
{id:'classic',name:'Classic Sourdough',cat:'sourdough',price:150,half:80,halfCost:0,halfName:'Classic Sourdough ครึ่งโลฟ',cost:0,stock:20,prep:'Japanese flour',desc:'Japanese flour',img:'assets/classic.svg',halfImg:'assets/classic.svg'},
{id:'wholewheat',name:'Whole wheat Sourdough',cat:'sourdough',price:180,half:100,halfCost:0,halfName:'Whole wheat Sourdough ครึ่งโลฟ',cost:0,stock:20,prep:'Japanese flour + 30% German whole wheat',desc:'Bestseller · Japanese flour + 30% German whole wheat',img:'assets/wholewheat.svg',halfImg:'assets/wholewheat.svg'},
{id:'multigrain',name:'Multigrain Sourdough',cat:'sourdough',price:190,half:110,halfCost:0,halfName:'Multigrain Sourdough ครึ่งโลฟ',cost:0,stock:20,prep:'',desc:'',img:'assets/multigrain.svg',halfImg:'assets/multigrain.svg'},
{id:'sesame',name:'Black Sesame Sourdough',cat:'sourdough',price:190,half:110,halfCost:0,halfName:'Black Sesame Sourdough ครึ่งโลฟ',cost:0,stock:20,prep:'',desc:'',img:'assets/sesame.svg',halfImg:'assets/sesame.svg'},
{id:'cranberry',name:'Cranberry Sourdough',cat:'sourdough',price:190,half:110,halfCost:0,halfName:'Cranberry Sourdough ครึ่งโลฟ',cost:0,stock:20,prep:'',desc:'',img:'assets/cranberry.svg',halfImg:'assets/cranberry.svg'},
{id:'walnut',name:'Cranberry Walnuts Sourdough',cat:'sourdough',price:240,half:130,halfCost:0,halfName:'Cranberry Walnuts Sourdough ครึ่งโลฟ',cost:0,stock:20,prep:'',desc:'',img:'assets/walnut.svg',halfImg:'assets/walnut.svg'},
{id:'milk',name:'Fresh milk bread',cat:'bread',price:100,half:null,halfCost:0,halfName:'',cost:0,stock:20,prep:'',desc:'',img:'assets/milk.svg',halfImg:''},
{id:'wheatbread',name:'Whole wheat bread',cat:'bread',price:120,half:null,halfCost:0,halfName:'',cost:0,stock:20,prep:'',desc:'',img:'assets/wheatbread.svg',halfImg:''},
{id:'nosugar',name:'Whole wheat no sugar',cat:'bread',price:120,half:null,halfCost:0,halfName:'',cost:0,stock:20,prep:'',desc:'',img:'assets/nosugar.svg',halfImg:''},
{id:'brownie',name:'Brownie',cat:'bakery',price:10,half:null,halfCost:0,halfName:'',cost:0,stock:30,prep:'',desc:'',img:'assets/brownie.svg',halfImg:''},
{id:'buttercookie',name:'Butter cookie',cat:'bakery',price:10,half:null,halfCost:0,halfName:'',cost:0,stock:30,prep:'',desc:'',img:'assets/buttercookie.svg',halfImg:''},
{id:'graincookie',name:'Multigrain cookie',cat:'bakery',price:15,half:null,halfCost:0,halfName:'',cost:0,stock:30,prep:'',desc:'',img:'assets/graincookie.svg',halfImg:''},
{id:'fries',name:'French fries',cat:'food',price:25,half:null,halfCost:0,halfName:'',cost:0,stock:30,prep:'Small',desc:'Small',img:'assets/fries.svg',halfImg:''}
];
const baseProducts=(old?.products?.length?old.products:structuredClone(defaultProducts)); baseProducts.forEach(p=>{if(p.prep===undefined)p.prep=p.desc||''});
let db=JSON.parse(localStorage.getItem('sdpos_v32')||'null')||{accounts:baseAccounts,categories:old?.categories||baseCats,products:baseProducts,orders:old?.orders||[],promptpay:old?.promptpay||'',shopName:'Sourdough',printerWidth:80,held:[],preorders:[],qrImage:''}; db.shopName=db.shopName||'Sourdough'; db.printerWidth=db.printerWidth||80;
for(const k of ['accounts','categories','products','orders','held','preorders']) if(!db[k]) db[k]=[];
// V5.0 migration: older builds could save an empty product list. Seed the real shop menu only when there are no products, without overwriting an existing/custom menu.
if(!db.products.length){db.products=structuredClone(defaultProducts);localStorage.setItem('sdpos_v32',JSON.stringify(db));}
let cart=[],currentUser=null,currentCat='all',method='cash',received='0',currentOrderTab='history',preCart=[];
const save=()=>localStorage.setItem('sdpos_v32',JSON.stringify(db)); const total=()=>cart.reduce((a,x)=>a+x.qty*x.price,0); const qty=()=>cart.reduce((a,x)=>a+x.qty,0); const dateKey=d=>{let x=new Date(d),y=x.getFullYear(),m=String(x.getMonth()+1).padStart(2,'0'),day=String(x.getDate()).padStart(2,'0');return `${y}-${m}-${day}`};
let audioCtx=null;function clickSound(freq=520,dur=.045){try{audioCtx=audioCtx||new (window.AudioContext||window.webkitAudioContext)();let o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.value=freq;g.gain.value=.035;o.connect(g);g.connect(audioCtx.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+dur);o.stop(audioCtx.currentTime+dur)}catch(e){}}
function speakThai(text){try{speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(text);u.lang='th-TH';u.rate=.95;speechSynthesis.speak(u)}catch(e){}}
document.addEventListener('click',e=>{if(e.target.closest('button,summary,.product,.stockCheck'))clickSound()},true);
function iconPayment(m){return `<span class="payIcon ${m}"><svg><use href="#${m==='cash'?'cash':'qr'}"/></svg>${m==='cash'?'เงินสด':'QR'}</span>`}
function renderLoginUsers(){ $('#loginUser').innerHTML=db.accounts.map((a,i)=>`<option value="${i}">${a.u}</option>`).join('') }
function login(){let a=db.accounts[+$('#loginUser').value];if(!a||a.p!==$('#loginPass').value){$('#loginError').textContent='Incorrect login information';return}currentUser=a;$('#login').classList.add('hidden');$('#app').classList.remove('hidden');$('#who').textContent=a.name;$('#loginError').textContent='';go('sell');renderAll()}
const loginPass=$('#loginPass'); loginPass.disabled=false; loginPass.readOnly=false; loginPass.removeAttribute('readonly'); $('#loginBtn').addEventListener('click',login); loginPass.addEventListener('keydown',e=>{if(e.key==='Enter')login()}); $('#togglePass').addEventListener('click',()=>{loginPass.type=loginPass.type==='password'?'text':'password';loginPass.focus()}); $('#logout').onclick=()=>{currentUser=null;$('#app').classList.add('hidden');$('#login').classList.remove('hidden');$('#loginPass').value=''};
function go(id){$$('.page').forEach(x=>x.classList.toggle('active',x.id===id));$$('nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===id));$('#app').classList.toggle('sellMode',id==='sell');if(id==='orders')renderOrderTab();if(id==='reports')renderReports();if(id==='stock')renderStock();if(id==='manage')renderManage();if(id==='settings')renderSettings()}
$$('nav button').forEach(b=>b.onclick=()=>go(b.dataset.page)); setInterval(()=>$('#clock').textContent=new Date().toLocaleString('th-TH',{dateStyle:'medium',timeStyle:'short'}),1000);
function renderCats(){let arr=[...db.categories,{id:'all',name:'ทั้งหมด'}];$('#categoryNav').innerHTML=arr.map(c=>`<button class="${currentCat===c.id?'active':''}" data-cat="${c.id}">${c.name}</button>`).join('');$$('#categoryNav button').forEach(b=>b.onclick=()=>{currentCat=b.dataset.cat;renderCats();renderProducts()})}
function renderProducts(){let q=$('#search').value.toLowerCase();let ps=db.products.filter(p=>(currentCat==='all'||p.cat===currentCat)&&p.name.toLowerCase().includes(q));$('#products').innerHTML=ps.map(p=>`<button class="product ${p.stock<=0?'soldOut':''}" data-id="${p.id}" ${p.stock<=0?'disabled':''}><img src="${p.img||'logo.png'}"><div class="pBody"><h3>${p.name}</h3><p>${p.desc||''}</p><div class="pFoot"><b>${money(p.price)}</b>${p.half?`<span>ครึ่ง ${money(p.half)}</span>`:''}</div><small>คงเหลือ ${p.stock}</small></div></button>`).join('')||'<div class="emptyState">ไม่พบสินค้า</div>';$$('.product').forEach(b=>b.onclick=()=>chooseProduct(b.dataset.id))}
$('#search').oninput=renderProducts;
function chooseProduct(id){let p=db.products.find(x=>x.id===id);if(p.half){$('#variantChoices').innerHTML=`<button onclick="pickVariant('${id}','half')"><img src="${p.halfImg||p.img||'logo.png'}"><b>${p.halfName||'ครึ่งโลฟ'}</b><strong>${money(p.half)}</strong></button><button onclick="pickVariant('${id}','full')"><img src="${p.img||'logo.png'}"><b>เต็มโลฟ</b><strong>${money(p.price)}</strong></button>`;$('#variantModal').classList.remove('hidden')}else addCart(p,'',p.price)}
window.pickVariant=(id,v)=>{let p=db.products.find(x=>x.id===id);addCart(p,v==='half'?(p.halfName||'ครึ่งโลฟ'):'เต็มโลฟ',v==='half'?p.half:p.price);$('#variantModal').classList.add('hidden')};
function addCart(p,variant,price){let key=p.id+'|'+variant,x=cart.find(i=>i.key===key);if(x)x.qty++;else cart.push({key,id:p.id,name:p.name,variant,price,qty:1});renderCart();$('#salePulse').innerHTML=`เพิ่ม <b>${p.name}</b> · ในออเดอร์ ${qty()} ชิ้น`;$('#salePulse').classList.add('flash');setTimeout(()=>$('#salePulse').classList.remove('flash'),500)}
let currentOrderNo=null;
function renderCart(){if(currentOrderNo==null)currentOrderNo=nextId();let n=qty();$('#itemCount').textContent=n+' ชิ้น';$('#total').textContent=money(total());$('#orderNo').textContent='#'+String(currentOrderNo).padStart(3,'0');$('#cartItems').innerHTML=cart.length?cart.map((x,i)=>`<div class="cartLine"><div><b>${x.name}</b><small>${x.variant||'ปกติ'} · ${money(x.price)}</small><div class="qty"><button data-i="${i}" data-d="-1">−</button><strong>${x.qty}</strong><button data-i="${i}" data-d="1">+</button></div></div><b>${money(x.qty*x.price)}</b></div>`).join(''):'<div class="emptyState"><svg><use href="#cart"/></svg><b>ยังไม่มีสินค้า</b><span>เลือกเมนูเพื่อเริ่มขาย</span></div>';$$('.qty button').forEach(b=>b.onclick=()=>{let i=+b.dataset.i;cart[i].qty+=+b.dataset.d;if(cart[i].qty<=0)cart.splice(i,1);renderCart()});renderHeld()}
function nextId(){return Math.max(0,...db.orders.map(o=>+o.id||0),...db.held.map(h=>+h.orderNo||0))+1}
$('#clear').onclick=()=>{cart=[];renderCart();$('#salePulse').textContent='ล้างรายการแล้ว'};
$('#cancelBtn').onclick=()=>{if(!cart.length)return;if(!confirm('ลูกค้ายกเลิกออเดอร์ปัจจุบัน?'))return;let now=new Date(),cancelledOrder={id:currentOrderNo||nextId(),date:now.toISOString(),localDate:dateKey(now),staff:currentUser.name,method:'cancelled',total:total(),received:0,change:0,status:'cancelled',cancelSource:'sell',cancelReason:'ลูกค้ายกเลิกก่อนชำระเงิน',items:structuredClone(cart)};db.orders.push(cancelledOrder);cart=[];currentOrderNo=null;save();renderCart();$('#salePulse').textContent='บันทึก Order #'+String(cancelledOrder.id).padStart(3,'0')+' เป็นยกเลิกแล้ว';clickSound(320,.12)};
$('#holdBtn').onclick=()=>{if(!cart.length)return alert('ยังไม่มีสินค้า');if(currentOrderNo==null)currentOrderNo=nextId();db.held.push({id:Date.now(),orderNo:currentOrderNo,time:new Date().toISOString(),items:structuredClone(cart),staff:currentUser.name});cart=[];currentOrderNo=null;save();renderCart();$('#salePulse').textContent='พัก Order #'+String(db.held[db.held.length-1].orderNo).padStart(3,'0')+' แล้ว'};
function renderHeld(){let hc=db.held.length;let hcEl=$('#heldCount');if(hcEl){hcEl.textContent=hc;hcEl.classList.toggle('isZero',hc===0)}let fb=$('#heldFloatBadge');if(fb){fb.textContent=hc;fb.classList.toggle('hidden',hc===0)}let nb=$('#heldNavBtn');if(nb)nb.classList.toggle('hasHeld',hc>0);$('#heldOrders').innerHTML=db.held.map((h,i)=>{let qty=h.items.reduce((a,x)=>a+x.qty,0),total=h.items.reduce((a,x)=>a+x.qty*x.price,0),names=h.items.slice(0,2).map(x=>x.name).join(' · '),more=h.items.length>2?` +${h.items.length-2} รายการ`:'';return `<article class="heldCard"><div class="heldCardTop"><div class="heldOrderLabels"><span class="heldOrderNo">Order #${String(h.orderNo||i+1).padStart(3,'0')}</span><span class="heldQueueNo">พักลำดับ ${i+1}</span></div><span class="heldDot"></span></div><b class="heldNames">${names||'ออเดอร์พัก'}${more}</b><div class="heldMeta"><span>${qty} ชิ้น</span><strong>${money(total)}</strong></div><button class="heldResume" onclick="resumeHeld(${i})">เรียกออเดอร์กลับมา</button></article>`}).join('')||'<div class="heldEmpty"><div class="heldEmptyIcon">✓</div><b>ไม่มีออเดอร์พัก</b><span>ออเดอร์ที่พักไว้จะแสดงตรงนี้</span></div>'}
window.resumeHeld=i=>{if(cart.length&&!confirm('มีออเดอร์ปัจจุบัน ต้องการแทนที่ด้วยออเดอร์พัก?'))return;let held=db.held[i];cart=held.items;currentOrderNo=held.orderNo||nextId();db.held.splice(i,1);save();renderCart();$('#salePulse').textContent='เรียก Order #'+String(currentOrderNo).padStart(3,'0')+' กลับมาแล้ว'};
$('#payBtn').onclick=()=>{if(!cart.length)return alert('กรุณาเลือกสินค้า');received='0';method='cash';$('#payTotal').textContent=money(total());$('#payModal').classList.remove('hidden');setMethod('cash');renderKeypad()};
$$('.method button').forEach(b=>b.onclick=()=>setMethod(b.dataset.method));function setMethod(m){method=m;$$('.method button').forEach(b=>b.classList.toggle('active',b.dataset.method===m));$('#cashArea').classList.toggle('hidden',m!=='cash');$('#qrArea').classList.toggle('hidden',m!=='qr');if(m==='qr')renderQR()}
function setReceived(v){received=String(Math.max(0,+v||0));$('#receivedDisplay').textContent=money(received);$('#change').textContent=money(Math.max(0,+received-total()))}
function renderKeypad(){let input=$('#cashInput'),modal=$('#cashPadModal'),keys=$('#cashPadKeys');$('#quickCash').innerHTML=[20,50,100,500,1000].map(v=>`<button data-v="${v}">${v}</button>`).join('')+`<button data-exact="1" class="exactCash">พอดี</button>`;$$('#quickCash [data-v]').forEach(b=>b.onclick=()=>{input.value=b.dataset.v;setReceived(input.value)});$('#quickCash [data-exact]').onclick=()=>{input.value=total();setReceived(total())};keys.innerHTML=['1','2','3','4','5','6','7','8','9','⌫','0','ล้าง'].map(k=>`<button data-key="${k}" class="${k==='⌫'?'keyDelete':k==='ล้าง'?'keyClear':''}">${k}</button>`).join('');input.value='';function refreshPad(){$('#cashPadValue').textContent=money(+(input.value||0));setReceived(input.value||0)}function openPad(){modal.classList.remove('hidden');refreshPad();clickSound(620,.04)}input.onclick=openPad;input.onfocus=()=>input.blur();keys.querySelectorAll('button').forEach(b=>b.onclick=()=>{let k=b.dataset.key;if(k==='⌫')input.value=input.value.slice(0,-1);else if(k==='ล้าง')input.value='';else input.value=(input.value==='0'?'':input.value)+k;refreshPad();clickSound(680,.035)});$('#cashPadExact').onclick=()=>{input.value=total();refreshPad();clickSound(760,.05)};$('#cashPadUse').onclick=()=>{modal.classList.add('hidden');refreshPad();clickSound(820,.06)};$('#cashPadClose').onclick=()=>modal.classList.add('hidden');modal.onclick=e=>{if(e.target===modal)modal.classList.add('hidden')};setReceived(0)}
function crc16(s){let crc=0xffff;for(let c of s){crc^=c.charCodeAt(0)<<8;for(let i=0;i<8;i++)crc=(crc&0x8000)?(crc<<1)^0x1021:crc<<1,crc&=0xffff}return crc.toString(16).toUpperCase().padStart(4,'0')}
function tlv(id,val){return id+String(val.length).padStart(2,'0')+val}
function promptPayPayload(id,amount){let x=(id||'').replace(/\D/g,'');if(!x)return '';let target=x.length===10?'0066'+x.slice(1):x.length===13?x:'';if(!target)return '';let aid=tlv('00','A000000677010111')+(x.length===10?tlv('01',target):tlv('02',target));let s=tlv('00','01')+tlv('01','12')+tlv('29',aid)+tlv('53','764')+tlv('54',Number(amount).toFixed(2))+tlv('58','TH')+tlv('59',(db.shopName||'SOURDOUGH').toUpperCase().replace(/[^A-Z0-9 ]/g,'').slice(0,25)||'SOURDOUGH')+tlv('60','THAILAND')+'6304';return s+crc16(s)}
function drawQR(el,payload,size){el.innerHTML='';if(!payload){el.innerHTML='<div class="qrWarn">ยังไม่ได้ตั้งค่า PromptPay</div>';return}if(window.QRCode)new QRCode(el,{text:payload,width:size,height:size,colorDark:'#2b1d14',colorLight:'#fff'});else el.innerHTML='<div class="qrWarn">ต้องเชื่อมอินเทอร์เน็ตครั้งแรกเพื่อโหลดตัวสร้าง QR</div>'}
function renderQR(){let p=promptPayPayload(db.promptpay,total());$('#qrAmount').textContent=money(total());if(db.qrImage){$('#qrStatus').textContent='QR รูปภาพของร้าน · กรุณาตรวจสอบยอด '+money(total());$('#qrcode').innerHTML=`<img src="${db.qrImage}" style="width:220px;height:220px;object-fit:contain;border-radius:12px">`;$('#qrcodeFull').innerHTML=`<img src="${db.qrImage}" style="width:340px;height:340px;object-fit:contain;border-radius:16px">`}else{$('#qrStatus').textContent=db.promptpay?'PromptPay: '+db.promptpay:'กรุณาตั้ง PromptPay ในหน้าตั้งค่า';drawQR($('#qrcode'),p,220);drawQR($('#qrcodeFull'),p,340)}$('#qrFullAmount').textContent=money(total())}
$('#qrZoom').onclick=()=>{renderQR();$('#qrFull').classList.remove('hidden')};
$('#confirmPay').onclick=()=>{if(method==='cash'&&+received<total())return alert('จำนวนเงินไม่พอ');if(method==='qr'&&!db.qrImage&&!promptPayPayload(db.promptpay,total()))return alert('กรุณาตั้งค่า PromptPay หรือใส่รูป QR ก่อน');let now=new Date(),o={id:currentOrderNo||nextId(),date:now.toISOString(),localDate:dateKey(now),staff:currentUser.name,method,total:total(),received:method==='cash'?+received:total(),change:method==='cash'?+received-total():0,status:'paid',items:structuredClone(cart)};db.orders.push(o);currentOrderNo=null;o.items.forEach(i=>{let p=db.products.find(x=>x.id===i.id);if(p)p.stock=Math.max(0,p.stock-i.qty)});save();cart=[];renderCart();renderProducts();$('#payModal').classList.add('hidden');$('#successOrder').textContent='Order #'+String(o.id).padStart(3,'0');$('#successAmount').textContent=money(o.total);$('#successPaid').textContent=money(o.received);$('#successChange').textContent=money(o.change);$('#successModal').classList.remove('hidden');startSuccessCountdown();$('#successPrint').onclick=()=>window.printReceipt(o.id);$('#successNew').onclick=()=>closeSuccessAndReset();clickSound(880,.18);speakThai(`${o.method==='cash'?'เงินสด':'เงินโอน'} ${o.total} บาท ชำระเงินสำเร็จ${o.change?` เงินทอน ${o.change} บาท`:''}`)};
$$('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).classList.add('hidden'));
$$('[data-otab]').forEach(b=>b.onclick=()=>{currentOrderTab=b.dataset.otab;$$('[data-otab]').forEach(x=>x.classList.toggle('active',x===b));renderOrderTab()});
function renderOrderTab(){if(currentOrderTab==='history')renderOrders();else if(currentOrderTab==='preorder')renderPreorders();else renderKitchen()}
function renderOrders(){let os=[...db.orders].reverse();$('#orderTab').innerHTML=`<div class="orderList">${os.map(o=>`<details class="orderCard orderDrop"><summary><div><h3>#${String(o.id).padStart(3,'0')} · ${money(o.total)}</h3><p>${new Date(o.date).toLocaleString('th-TH')} · ${o.staff}</p></div><div class="orderSummaryRight">${o.status==='cancelled'?'':iconPayment(o.method)}${o.status==='cancelled'?'<span class="cancelBadge">ยกเลิก</span>':''}<span class="chev">⌄</span></div></summary><div class="orderItems">${o.items.map(i=>`<div><span>${i.qty} × ${i.name}${i.variant?' · '+i.variant:''}</span><b>${money(i.qty*i.price)}</b></div>`).join('')}</div>${o.status==='cancelled'?`<div class="cancelNotice"><b>ยกเลิก</b><span>${o.cancelReason||'ออเดอร์นี้ถูกยกเลิก'}</span></div>`:''}<div class="actions"><button onclick="printReceipt(${o.id})"><svg><use href="#print"/></svg>ใบเสร็จ</button><button class="warm" onclick="printKitchen(${o.id})"><svg><use href="#chef"/></svg>พิมพ์เตรียมอาหาร</button>${o.status!=='cancelled'?`<button class="danger" onclick="cancelPaid(${o.id})">ยกเลิกออเดอร์</button>`:'<span class="cancelBadge cancelBadgeAction">ยกเลิกแล้ว</span>'}</div></details>`).join('')||'<div class="emptyState">ยังไม่มีออเดอร์</div>'}</div>`}
window.cancelPaid=id=>{let o=db.orders.find(x=>x.id===id);if(!o||o.status==='cancelled'||!confirm('ยกเลิกออเดอร์นี้?'))return;o.status='cancelled';save();renderOrders()};
function printDoc(html){$('#printArea').innerHTML=html;document.body.classList.add('printing');setTimeout(()=>{window.print();setTimeout(()=>document.body.classList.remove('printing'),300)},100)}
window.printReceipt=id=>{let o=db.orders.find(x=>x.id===id);printDoc(`<div class="ticket"><img src="logo.png"><h2>Sourdough</h2><p>Order #${String(o.id).padStart(3,'0')}</p><hr>${o.items.map(i=>`<div class="r"><span>${i.qty} × ${i.name} ${i.variant||''}</span><b>${money(i.qty*i.price)}</b></div>`).join('')}<hr><div class="r"><b>TOTAL</b><b>${money(o.total)}</b></div><div>${o.method==='cash'?'เงินสด':'PromptPay QR'}${o.method==='cash'?` · ทอน ${money(o.change)}`:''}</div><p>Thank you</p></div>`)};
window.printKitchen=id=>{let o=db.orders.find(x=>x.id===id);printDoc(`<div class="ticket kitchenTicket"><h1>KITCHEN</h1><h2>Order #${String(o.id).padStart(3,'0')}</h2><p>${new Date(o.date).toLocaleString('th-TH')}</p><hr>${o.items.map(i=>`<div class="kitem"><b>${i.qty} × ${i.name}</b><span>${i.variant||''}</span></div>`).join('')}</div>`)};
function renderPreorders(){$('#orderTab').innerHTML=`<div class="pageHead"><div><h2>รายการสั่งล่วงหน้า</h2><p>ชื่อลูกค้า วันที่ เวลา เมนู และหมายเหตุ</p></div><button id="newPre" class="primary"><svg><use href="#calendar"/></svg>สร้างออเดอร์ล่วงหน้า</button></div><div class="orderList">${[...db.preorders].sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)).map(p=>`<article class="orderCard"><div class="orderTop"><div><h3>${p.customer}</h3><p>${p.date} · ${p.time}${p.phone?' · '+p.phone:''}</p></div><span class="preBadge">จองล่วงหน้า</span></div><div class="orderItems">${p.items.map(i=>`<div><span>${i.qty} × ${i.name} ${i.variant||''}</span><b>${money(i.qty*i.price)}</b></div>`).join('')}</div>${p.note?`<div class="note">หมายเหตุ: ${p.note}</div>`:''}<div class="actions"><button class="warm" onclick="printPreKitchen(${p.id})"><svg><use href="#print"/></svg>พิมพ์เตรียมอาหาร</button><button class="danger" onclick="deletePre(${p.id})">ลบ</button></div></article>`).join('')||'<div class="emptyState">ยังไม่มีรายการสั่งล่วงหน้า</div>'}</div>`;$('#newPre').onclick=openPreorder}
function openPreorder(){preCart=[];$('#preName').value='';$('#prePhone').value='';$('#preDate').value=dateKey(new Date());$('#preTime').value='10:00';$('#preNote').value='';renderPreProducts();$('#preorderModal').classList.remove('hidden')}
function renderPreProducts(){$('#preProducts').innerHTML=db.products.map(p=>{let x=preCart.find(i=>i.id===p.id);return `<button type="button" data-id="${p.id}"><span>${p.name}</span><b>${x?x.qty:0}</b></button>`}).join('');$$('#preProducts button').forEach(b=>b.onclick=()=>{let p=db.products.find(x=>x.id===b.dataset.id),x=preCart.find(x=>x.id===p.id);if(x)x.qty++;else preCart.push({id:p.id,name:p.name,variant:'',price:p.price,qty:1});renderPreProducts()})}
$('#preorderForm').onsubmit=e=>{e.preventDefault();if(!preCart.length)return alert('กรุณาเลือกเมนู');db.preorders.push({id:Date.now(),customer:$('#preName').value,phone:$('#prePhone').value,date:$('#preDate').value,time:$('#preTime').value,note:$('#preNote').value,items:structuredClone(preCart)});save();$('#preorderModal').classList.add('hidden');renderPreorders();clickSound(760,.12);speakThai('มีรายการสั่งล่วงหน้าใหม่')};
window.deletePre=id=>{db.preorders=db.preorders.filter(x=>x.id!==id);save();renderPreorders()};window.printPreKitchen=id=>{let p=db.preorders.find(x=>x.id===id);printDoc(`<div class="ticket kitchenTicket"><h1>PRE-ORDER</h1><h2>${p.customer}</h2><h3>${p.date} · ${p.time}</h3><hr>${p.items.map(i=>`<div class="kitem"><b>${i.qty} × ${i.name}</b></div>`).join('')}<hr><b>หมายเหตุ: ${p.note||'-'}</b></div>`)};
function renderKitchen(){let active=db.orders.filter(o=>o.status==='paid').slice(-20).reverse();$('#orderTab').innerHTML=`<div class="kitchenGrid"><div><h2>รายการที่ต้องเตรียม</h2>${active.map(o=>`<details class="kitchenDrop"><summary><b>Order #${String(o.id).padStart(3,'0')}</b><span>${o.items.reduce((a,i)=>a+i.qty,0)} ชิ้น⌄</span></summary><div class="kitchenInner">${o.items.map(i=>`<div><b>${i.qty} × ${i.name}</b><span>${i.variant||''}</span></div>`).join('')}<button class="warm" onclick="printKitchen(${o.id})"><svg><use href="#print"/></svg>พิมพ์ใบเตรียม</button></div></details>`).join('')||'<div class="emptyState">ไม่มีรายการ</div>'}</div><div><h2>ข้อมูลวัตถุดิบ / การเตรียม</h2>${db.categories.map(c=>`<section class="ingredientGroup"><h3>${c.name}</h3>${db.products.filter(p=>p.cat===c.id).map(p=>`<div><b>${p.name}</b><span>${p.prep||p.desc||'ยังไม่ได้ระบุ'}</span></div>`).join('')}</section>`).join('')}</div></div>`}
function statsFor(key){let os=db.orders.filter(o=>o.localDate===key),paid=os.filter(o=>o.status!=='cancelled'),cash=paid.filter(o=>o.method==='cash').reduce((a,o)=>a+o.total,0),qr=paid.filter(o=>o.method==='qr').reduce((a,o)=>a+o.total,0),sales=cash+qr,cost=0;paid.forEach(o=>o.items.forEach(i=>{let p=db.products.find(p=>p.id===i.id);cost+=(i.variant==='ครึ่งโลฟ'?(p?.halfCost??(p?.cost||0)/2):(p?.cost||0))*i.qty}));return {os,paid,cash,qr,sales,cost,profit:sales-cost,cancelled:os.length-paid.length}}
function statHtml(s){return `<div><span>ยอดขายรวม</span><b>${money(s.sales)}</b></div><div><span>เงินสด</span><b>${money(s.cash)}</b></div><div><span>QR</span><b>${money(s.qr)}</b></div><div><span>ออเดอร์สำเร็จ</span><b>${s.paid.length} ออเดอร์</b></div><div><span>ต้นทุน</span><b>${money(s.cost)}</b></div><div><span>กำไรโดยประมาณ</span><b>${money(s.profit)}</b></div><div><span>ยกเลิก</span><b>${s.cancelled} ออเดอร์</b></div>`}
function renderReports(){let today=dateKey(new Date());$('#todayStats').innerHTML=statHtml(statsFor(today));if(!$('#reportDate').value)$('#reportDate').value=today;renderPast()}
function renderPast(){let key=$('#reportDate').value,s=statsFor(key);$('#pastStats').innerHTML=statHtml(s);let rows={};s.paid.forEach(o=>o.items.forEach(i=>{let k=i.id+'|'+i.variant;if(!rows[k])rows[k]={name:i.name+(i.variant?' · '+i.variant:''),qty:0,total:0,cash:0,qr:0};rows[k].qty+=i.qty;rows[k].total+=i.qty*i.price;rows[k][o.method]+=i.qty*i.price}));$('#productSales').innerHTML=`<div class="tr th"><span>สินค้า</span><span>จำนวน</span><span>ชำระ</span><span>ยอด</span></div>`+Object.values(rows).map(r=>`<div class="tr"><span>${r.name}</span><span>${r.qty}</span><span>${r.cash?iconPayment('cash'):''}${r.qr?iconPayment('qr'):''}</span><b>${money(r.total)}</b></div>`).join('')}
$('#reportDate').onchange=renderPast;$('#printSummary').onclick=()=>{let k=dateKey(new Date()),s=statsFor(k);printDoc(`<div class="ticket"><img src="logo.png"><h2>สรุปปิดยอด ${k}</h2><hr><div class="r"><span>ยอดขาย</span><b>${money(s.sales)}</b></div><div class="r"><span>เงินสด</span><b>${money(s.cash)}</b></div><div class="r"><span>QR</span><b>${money(s.qr)}</b></div><div class="r"><span>ต้นทุน</span><b>${money(s.cost)}</b></div><div class="r"><span>กำไรโดยประมาณ</span><b>${money(s.profit)}</b></div><div class="r"><span>ออเดอร์</span><b>${s.paid.length}</b></div><div class="r"><span>ยกเลิก</span><b>${s.cancelled}</b></div></div>`)};
let selectedStock=new Set();
function renderStock(){
  $('#stockList').innerHTML=db.categories.map(c=>`<section class="stockGroup"><h3>${c.name}</h3>${db.products.filter(p=>p.cat===c.id).map(p=>`<div class="stockRow ${selectedStock.has(p.id)?'selected':''}" data-stock-id="${p.id}"><div class="stockPick" onclick="toggleStockPick('${p.id}')"><b>${p.name}</b><span>${p.stock<=3?'สต๊อกต่ำ':''}</span><small>${selectedStock.has(p.id)?'เลือกแล้ว — ใช้ปุ่มด้านบนปรับพร้อมกัน':'แตะชื่อเพื่อเลือก'}</small></div><button onclick="stockChange('${p.id}',-1)">−</button><strong>${p.stock}</strong><button onclick="stockChange('${p.id}',1)">+</button></div>`).join('')||'<small>ไม่มีสินค้า</small>'}</section>`).join('');
  $('#selectAllStock').textContent=selectedStock.size===db.products.length&&db.products.length?'ยกเลิกการเลือกทั้งหมด':'เลือกทั้งหมด';
}
window.toggleStockPick=id=>{selectedStock.has(id)?selectedStock.delete(id):selectedStock.add(id);renderStock()};
window.stockChange=(id,d)=>{let p=db.products.find(x=>x.id===id);p.stock=Math.max(0,+p.stock+d);save();renderStock();renderProducts()};
$('#selectAllStock').onclick=()=>{if(selectedStock.size===db.products.length)selectedStock.clear();else db.products.forEach(p=>selectedStock.add(p.id));renderStock()};
function bulk(d){selectedStock.forEach(id=>{let p=db.products.find(p=>p.id===id);if(p)p.stock=Math.max(0,+p.stock+d)});save();renderStock();renderProducts()}
$('#bulkPlus').onclick=()=>bulk(1);$('#bulkMinus').onclick=()=>bulk(-1);
function renderManage(){ $('#categoryManager').innerHTML=db.categories.map(c=>`<button onclick="filterManage('${c.id}')">${c.name}</button>`).join('');renderManageList('all') }
window.filterManage=cat=>renderManageList(cat);function renderManageList(cat){let ps=db.products.filter(p=>cat==='all'||p.cat===cat);$('#menuManager').innerHTML=ps.map(p=>`<div class="manageRow"><img src="${p.img||'logo.png'}"><div><b>${p.name}</b><span>${db.categories.find(c=>c.id===p.cat)?.name||p.cat} · ${money(p.price)} · Stock ${p.stock}</span></div><button onclick="editProduct('${p.id}')">แก้ไข</button><button class="danger" onclick="deleteProduct('${p.id}')">ลบ</button></div>`).join('')}
$('#addCategory').onclick=()=>{const m=$('#categoryModal'),i=$('#newCategoryName');m.classList.remove('hidden');i.value='';setTimeout(()=>i.focus(),80)};$('#cancelCategory').onclick=()=>$('#categoryModal').classList.add('hidden');$('#confirmCategory').onclick=()=>{let name=$('#newCategoryName').value.trim();if(!name)return $('#newCategoryName').focus();if(db.categories.some(c=>c.name.toLowerCase()===name.toLowerCase()))return alert('มีหมวดหมู่นี้อยู่แล้ว');db.categories.push({id:'cat'+Date.now(),name});save();$('#categoryModal').classList.add('hidden');renderManage();renderCats();clickSound(720,.08)};$('#newCategoryName').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();$('#confirmCategory').click()}});$('#addProduct').onclick=()=>openEditor();
function fillCatSelect(){ $('#editCategory').innerHTML=db.categories.map(c=>`<option value="${c.id}">${c.name}</option>`).join('') }
function openEditor(p){fillCatSelect();$('#imagePreview').dataset.cropped='';$('#halfImagePreview').dataset.cropped='';$('#editImage').value='';$('#editHalfImage').value='';$('#editorTitle').textContent=p?'แก้ไขเมนู':'เพิ่มเมนู';$('#editId').value=p?.id||'';$('#editName').value=p?.name||'';$('#editCategory').value=p?.cat||db.categories[0]?.id||'';$('#editPrice').value=p?.price||'';$('#editHalf').value=p?.half||'';$('#editHalfCost').value=p?.halfCost||'';$('#editHalfName').value=p?.halfName||'ครึ่งโลฟ';$('#editCost').value=p?.cost||'';$('#halfImagePreview').innerHTML=p?.halfImg?`<img src="${p.halfImg}">`:'';$('#editStock').value=p?.stock??0;$('#editPrep').value=p?.prep||'';$('#imagePreview').innerHTML=p?.img?`<img src="${p.img}">`:'';$('#editorModal').classList.remove('hidden');if($('#hasHalf')){$('#hasHalf').checked=!!p?.half;$('#halfFields').classList.toggle('hidden',!$('#hasHalf').checked)}}
window.editProduct=id=>openEditor(db.products.find(p=>p.id===id));window.deleteProduct=id=>{if(confirm('ลบสินค้านี้?')){db.products=db.products.filter(p=>p.id!==id);save();renderManage();renderProducts()}};
$('#productForm').onsubmit=e=>{e.preventDefault();let id=$('#editId').value||'p'+Date.now(),oldp=db.products.find(p=>p.id===id),file=$('#editImage').files[0],halfFile=$('#editHalfImage').files[0],cropped=$('#imagePreview').dataset.cropped||null,halfCropped=$('#halfImagePreview').dataset.cropped||null;let build=(img,halfImg)=>{let p={id,name:$('#editName').value,cat:$('#editCategory').value,price:+$('#editPrice').value,half:$('#editHalf').value?+$('#editHalf').value:null,halfCost:+$('#editHalfCost').value||0,halfName:$('#editHalfName').value||'ครึ่งโลฟ',cost:+$('#editCost').value||0,stock:+$('#editStock').value||0,prep:$('#editPrep').value,img:img||oldp?.img||'logo.png',halfImg:halfImg||oldp?.halfImg||img||oldp?.img||'logo.png',desc:oldp?.desc||''};if(oldp)Object.assign(oldp,p);else db.products.push(p);save();$('#editorModal').classList.add('hidden');renderManage();renderProducts()};let read=f=>new Promise(r=>{if(!f)return r(null);let x=new FileReader();x.onload=()=>r(x.result);x.readAsDataURL(f)});Promise.all([read(file),read(halfFile)]).then(([a,b])=>build(cropped||a,halfCropped||b))};
function renderSettings(){$('#promptpay').value=db.promptpay||'';$('#shopName').value=db.shopName||'Sourdough';$('#printerWidth').value=String(db.printerWidth||80);renderQRImagePreview();renderSettingsQR();$('#accountSettings').innerHTML=db.accounts.map((a,i)=>`<div class="accountRow"><label>ชื่อแสดง<input id="an${i}" value="${a.name}"></label><label>Username<input id="au${i}" value="${a.u}"></label><label>Password<input id="ap${i}" value="${a.p}" inputmode="numeric"></label><button onclick="saveAccount(${i})">บันทึก</button></div>`).join('')}
window.saveAccount=i=>{let a=db.accounts[i];a.name=$('#an'+i).value.trim()||a.name;a.u=$('#au'+i).value.trim()||a.u;a.p=$('#ap'+i).value.trim()||a.p;save();renderLoginUsers();alert('บันทึกบัญชีแล้ว')};$('#savePrompt').onclick=()=>{let v=$('#promptpay').value.replace(/\D/g,'');if(v&&![10,13].includes(v.length))return alert('PromptPay ควรเป็นเบอร์โทร 10 หลัก หรือเลขบัตร/เลขผู้เสียภาษี 13 หลัก');db.promptpay=v;db.shopName=$('#shopName').value.trim()||'Sourdough';db.printerWidth=+$('#printerWidth').value||80;save();renderSettingsQR();document.querySelector('.brand b').textContent=db.shopName;alert('Saved. PromptPay QR has been updated automatically.')};
function renderAll(){renderLoginUsers();renderCats();renderProducts();renderCart()} renderLoginUsers(); renderAll();

function renderSettingsQR(){let el=$('#settingsQR');if(!el)return;if(db.qrImage){el.innerHTML='<small>ตัวอย่างรูป QR ที่ใช้ในหน้าชำระเงิน</small><div><img class="customSettingsQR" src="'+db.qrImage+'" alt="QR ร้าน"></div>';return}let p=promptPayPayload(db.promptpay,1);el.innerHTML='<small>ตัวอย่าง QR · ยอดจริงจะสร้างใหม่อัตโนมัติในหน้าขาย</small><div id="settingsQRCode"></div>';drawQR($('#settingsQRCode'),p,150)}
function renderQRImagePreview(){let el=$('#qrImagePreview'),rm=$('#removeQrImage');if(!el)return;el.innerHTML=db.qrImage?`<img src="${db.qrImage}" alt="QR ร้าน">`:'';rm?.classList.toggle('hidden',!db.qrImage)}
$('#qrImageInput')?.addEventListener('change',e=>{let f=e.target.files?.[0];if(!f)return;let r=new FileReader();r.onload=()=>{db.qrImage=r.result;save();renderQRImagePreview();renderSettingsQR();renderQR()};r.readAsDataURL(f)});
$('#removeQrImage')?.addEventListener('click',()=>{db.qrImage='';save();$('#qrImageInput').value='';renderQRImagePreview();renderSettingsQR();renderQR()});
$('#printerWidth')?.addEventListener('change',e=>{db.printerWidth=+e.target.value;save()});$('#testPrinter')?.addEventListener('click',()=>printDoc(`<div class="ticket kitchenTicket"><h1>${db.shopName||'Sourdough'}</h1><h2>AIMO D520 TEST</h2><p>Printer width: ${db.printerWidth||80} mm</p><hr><b>TEST PRINT OK</b></div>`));

/* v3.9 settings, export, half-loaf and receipt refinements */
(function(){
 const logo=document.querySelector('.loginLogo'); if(logo) logo.src='logo-transparent.png';
 const hasHalf=$('#hasHalf'), halfFields=$('#halfFields');
 function syncHalf(){if(!hasHalf||!halfFields)return;halfFields.classList.toggle('hidden',!hasHalf.checked);if(!hasHalf.checked){$('#editHalf').value='';$('#editHalfCost').value='';$('#editHalfName').value='';$('#editHalfImage').value='';$('#halfImagePreview').innerHTML=''}}
 if(hasHalf){hasHalf.onchange=syncHalf;}
 const oldOpen=window.openEditor||openEditor; window.openEditor=function(p){oldOpen(p);hasHalf.checked=!!p?.half;syncHalf()};
 document.querySelectorAll('[data-settings]').forEach(b=>b.onclick=()=>{document.querySelector('#settingsHome').style.display='none';document.querySelectorAll('.settingsPanel').forEach(x=>x.classList.toggle('active',x.dataset.panel===b.dataset.settings))});
 document.querySelectorAll('.settingsBack').forEach(b=>b.onclick=()=>{document.querySelectorAll('.settingsPanel').forEach(x=>x.classList.remove('active'));document.querySelector('#settingsHome').style.display='grid'});
 function rowsFor(k){let rows=[['Order','Date','Time','Staff','Payment','Product','Variant','Qty','Unit Price','Sales','Cost','Profit','Status']];db.orders.filter(o=>o.localDate===k).forEach(o=>o.items.forEach(i=>{let p=db.products.find(x=>x.id===i.id)||{};let c=(i.variant&&i.variant.includes('ครึ่ง'))?(p.halfCost||0):(p.cost||0);rows.push([String(o.id).padStart(3,'0'),k,new Date(o.date).toLocaleTimeString('th-TH'),o.staff,o.method==='cash'?'Cash':'PromptPay',i.name,i.variant||'',i.qty,i.price,i.qty*i.price,i.qty*c,i.qty*(i.price-c),o.status])}));return rows}
 function dl(name,content,type){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
 function csv(rows){return '\ufeff'+rows.map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\r\n')}
 $('#exportCSV').onclick=()=>{let k=$('#exportDate').value||dateKey(new Date());dl(`sourdough-sales-${k}.csv`,csv(rowsFor(k)),'text/csv;charset=utf-8')};
 $('#exportExcel').onclick=()=>{let k=$('#exportDate').value||dateKey(new Date()),r=rowsFor(k);let h='<table>'+r.map((x,i)=>'<tr>'+x.map(v=>`<${i?'td':'th'}>${String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;')}</${i?'td':'th'}>`).join('')+'</tr>').join('')+'</table>';dl(`sourdough-sales-${k}.xls`,h,'application/vnd.ms-excel')};
 $('#exportDate').value=dateKey(new Date());
})();

window.printReceipt=id=>{let o=db.orders.find(x=>x.id===id);if(!o)return;let dt=new Date(o.date);printDoc(`<div class="ticket"><img class="ticketLogo" src="logo-transparent.png"><div class="receiptTitle">${db.shopName||'Sourdough'} Takeaway</div><div class="receiptSub">ขนมปังดี เพื่อวันที่ดีกว่า</div><hr><div class="meta"><b>Order #${String(o.id).padStart(3,'0')}</b><span>${dt.toLocaleDateString('th-TH')} ${dt.toLocaleTimeString('th-TH',{hour:'2-digit',minute:'2-digit'})}</span></div><div class="meta"><span>Staff: ${o.staff}</span><span>Takeaway</span></div><hr>${o.items.map(i=>`<div class="r"><span>${i.qty}&nbsp;&nbsp; ${i.name}${i.variant?`<br><small>(${i.variant})</small>`:''}</span><b>${i.qty*i.price}</b></div>`).join('')}<hr><div class="r"><span>Subtotal</span><b>${o.total}</b></div><div class="r" style="font-size:18px"><b>Total</b><b>${money(o.total)}</b></div>${o.method==='cash'?`<div class="r"><span>Cash</span><b>${o.received}</b></div><div class="r"><b>Change</b><b>${o.change}</b></div>`:`<div class="r"><span>PromptPay QR</span><b>${o.total}</b></div>`}<hr><div class="thanks">Thank you ♡</div><div class="fresh">Fresh Bread<br>Happier People</div></div>`)};
$('#printSummary').onclick=()=>{let k=dateKey(new Date()),s=statsFor(k);printDoc(`<div class="ticket"><h2 style="text-align:center">${db.shopName||'Sourdough'}</h2><h3 style="text-align:center">สรุปปิดยอด ${k}</h3><hr><div class="r"><span>ยอดขาย</span><b>${money(s.sales)}</b></div><div class="r"><span>เงินสด</span><b>${money(s.cash)}</b></div><div class="r"><span>QR</span><b>${money(s.qr)}</b></div><div class="r"><span>ต้นทุน</span><b>${money(s.cost)}</b></div><div class="r"><span>กำไรโดยประมาณ</span><b>${money(s.profit)}</b></div><div class="r"><span>ออเดอร์</span><b>${s.paid.length}</b></div><div class="r"><span>ยกเลิก</span><b>${s.cancelled}</b></div></div>`)};


/* v4.0 image crop / resize */
(function(){
 const modal=$('#imageCropModal'),canvas=$('#cropCanvas'),ctx=canvas?.getContext('2d'),zoom=$('#cropZoom'),rx=$('#cropX'),ry=$('#cropY');
 if(!modal||!canvas||!ctx)return;
 let img=null,target=null;
 function draw(){if(!img)return;ctx.clearRect(0,0,640,640);ctx.fillStyle='#f5eee4';ctx.fillRect(0,0,640,640);let base=Math.max(640/img.naturalWidth,640/img.naturalHeight),sc=base*(+zoom.value||1),w=img.naturalWidth*sc,h=img.naturalHeight*sc,maxX=Math.max(0,(w-640)/2),maxY=Math.max(0,(h-640)/2),x=(640-w)/2+(+rx.value/100)*maxX,y=(640-h)/2+(+ry.value/100)*maxY;ctx.drawImage(img,x,y,w,h)}
 function close(){modal.classList.add('hidden');img=null;target=null}
 function openCrop(file,preview){if(!file)return;let r=new FileReader();r.onload=()=>{let im=new Image();im.onload=()=>{img=im;target=preview;zoom.value=1;rx.value=0;ry.value=0;modal.classList.remove('hidden');draw()};im.src=r.result};r.readAsDataURL(file)}
 [zoom,rx,ry].forEach(x=>x?.addEventListener('input',draw));
 $('#cropClose').onclick=close;$('#cropCancel').onclick=close;
 $('#cropApply').onclick=()=>{if(!img||!target)return;draw();let out=document.createElement('canvas');out.width=900;out.height=900;out.getContext('2d').drawImage(canvas,0,0,900,900);let data=out.toDataURL('image/jpeg',.9);target.dataset.cropped=data;target.innerHTML=`<img src="${data}" alt="รูปที่ครอปแล้ว">`;close()};
 $('#editImage').addEventListener('change',e=>openCrop(e.target.files[0],$('#imagePreview')));
 $('#editHalfImage').addEventListener('change',e=>openCrop(e.target.files[0],$('#halfImagePreview')));
})();

// V4.2: auto-close payment success screen after 5 seconds with animated countdown
let successTimer=null;
function closeSuccessAndReset(){
  if(successTimer){clearInterval(successTimer);successTimer=null}
  $('#successModal').classList.add('hidden');
  $('#salePulse').textContent='พร้อมรับออเดอร์ใหม่';
}
function startSuccessCountdown(){
  if(successTimer) clearInterval(successTimer);
  let remaining=5;
  const sec=$('#successSeconds'), ringSec=$('#ringSeconds'), ring=$('#countRingProgress');
  const circumference=2*Math.PI*18;
  const paint=()=>{if(sec)sec.textContent=remaining;if(ringSec)ringSec.textContent=remaining;if(ring)ring.style.strokeDashoffset=String(circumference*(1-remaining/5))};
  paint();
  successTimer=setInterval(()=>{remaining-=1;paint();if(remaining<=0){clearInterval(successTimer);successTimer=null;setTimeout(closeSuccessAndReset,180)}},1000);
}


// V4.4 held orders drawer from bottom navigation
(function(){
  const drawer=$('#heldDrawer'), backdrop=$('#heldDrawerBackdrop'), btn=$('#heldNavBtn'), close=$('#heldDrawerClose');
  function setHeldDrawer(open){if(!drawer)return;drawer.classList.toggle('open',open);if(backdrop)backdrop.classList.toggle('hidden',!open);}
  if(btn)btn.onclick=()=>{renderHeld();setHeldDrawer(!drawer.classList.contains('open'))};
  if(close)close.onclick=()=>setHeldDrawer(false);
  if(backdrop)backdrop.onclick=()=>setHeldDrawer(false);
})();

/* ===== V5.1: prevent pinch/double-tap zoom on touch devices ===== */
['gesturestart','gesturechange','gestureend'].forEach(function(type){
  document.addEventListener(type,function(e){ e.preventDefault(); },{passive:false});
});
let lastTouchEnd=0;
document.addEventListener('touchend',function(e){
  const now=Date.now();
  if(now-lastTouchEnd<=300){ e.preventDefault(); }
  lastTouchEnd=now;
},{passive:false});
